### ISSUE TITLE
Migrate from DynamoDB to MongoDB

### ISSUE THREAD

**Issue by asi345** [bounswe/2021SpringGroup7#102] opened 2021-05-25 18:56 UTC
We changed our database choice to MongoDB, the code will be updated according to it

**Comment by asi345** [comment] 2021-05-25 22:00
I changed the docker images and the code integration of the flask for database to completely use mongoDB. It is now ready and waiting for review.

**Comment by kocasariumut** [comment] 2021-05-26 21:14
It works as intended.

**Comment by mrabiabrn** [comment] 2021-05-26 21:54
Runned in my local and it works properly, closing the issue.

**Closed by mrabiabrn** 2021-05-26 21:54 UTC
Labels: Backend, Priority: High, Status: Waiting for Review, Type: Enhancement
